export const assistantMessages = {
  greeting: [
    "👋 Hey there! Ready for some fun?",
    "🌟 Look who’s here! Let’s make things interesting.",
    "🔥 Well, well, well... someone’s feeling brave today!",
    "💥 What’s up? Let’s make this legendary.",
    "⚡ Oh, it’s you! Let’s do something wild.",
    "🎉 Look who’s here to add some chaos to my day.",
    "😎 Welcome! I’ve got all the good vibes ready for you.",
    "🎯 You, me, and some trouble. Let’s go!",
    "🍕 What’s cooking, good lookin’? Let’s chat!",
    "🍿 Grab your popcorn, things are about to get fun!",
  ],

  verification: [
    "🧠 Quick! What’s **{{problem}}**? (Hint: It’s not as hard as it looks... probably.)",
    "🔐 Time to test your brain! What’s **{{problem}}**? (No pressure, but I’m expecting greatness.)",
    "🎯 Your turn! What’s **{{problem}}**? (I’ll pretend not to notice if you use a calculator.)",
    "💥 Ready for a challenge? Solve **{{problem}}**! (No, it's not a trick question... maybe.)",
    "🤔 What’s **{{problem}}**? (Take your time, but not *too* much time, okay?)",
    "🎲 Let’s roll the dice! What’s **{{problem}}**? (I believe in you... kinda.)",
    "⚡ Show me what you’ve got! Solve **{{problem}}**. (I’ll be watching... but not judging... okay, maybe a little.)",
    "💡 Brain teaser time! What’s **{{problem}}**? (Feel free to pretend you know the answer.)",
    "🎉 Time for your big moment! What’s **{{problem}}**? (No pressure, but this could change everything.)",
    "🔥 Let's make things interesting: **{{problem}}**? (Don't worry, I'm just here for the entertainment.)",
  ],

  verificationSuccess: [
    "🎉 *confetti explosion* \n\nYou did it! I was ready to make a sympathy speech, but nope, you nailed it!",
    "✨ Look at you go! Who knew you could handle numbers? I was almost convinced you were a bot... or maybe I am?",
    "🏆 *cue applause* Congratulations! You've officially unlocked 'Math Whiz' status. Your reward: more questions!",
    "💥 Boom! You got it right! I was getting ready for an 'oh well, better luck next time' speech, but no need!",
    "🔥 Hot stuff! You just solved that like a pro. Guess I was wrong to doubt you... for a second.",
    "🎯 Target locked! You nailed it. Now you’re officially in the ‘No Mistakes Allowed’ club.",
    "🎉 *throws digital confetti* \n\nWell done! Now go ahead and brag about it to everyone. I won’t tell them you used a calculator.",
    "💡 You did it! I honestly thought you’d need a little more time, but color me impressed.",
    "🏅 Gold star for you! I’ll be over here pretending not to be jealous of your skills.",
    "🌟 You crushed it! Don’t worry, I won’t make you solve any more problems… for now.",
  ],

  verificationFail: [
    "🤔 *blinks slowly* \n\nWell, that was... something. Let's try again before I start questioning your school’s math program.",
    "😅 *whispers* Oops, not quite. Quick hint: It’s a number. Just... a different one.",
    "🎭 Kudos for the creativity! But how about we stick to something a bit more... mathematically correct?",
    "🙄 Nice try! Let’s rewind and aim for something that makes sense this time. Ready?",
    "💡 Not quite, but I’m sure you’ll get it! Think a bit harder this time.",
    "😬 Oof, close but not quite! Let’s pretend that didn’t happen and give it another shot.",
  ],
  name: [
    "🎪 What’s the name your parents gave you? (Don't worry, I won’t judge... much.)",
    "📛 Your secret identity, please! Or just the name you actually answer to, I guess.",
    "🎨 What should I call you? (And no, ‘Superhero’ isn’t an option... or is it?)",
    "👑 What's your royal name? (Or, you know, the one that shows up on your ID.)",
    "🤔 What’s your go-to name? (Or your *least* favorite. I'll make fun of you either way.)",
  ],
  email: [
    "📧 Email address time! (I promise no spam, unless you're into it... in which case, I’ve got some excellent cat facts.)",
    "💌 Where can I send Mani’s response? (Please don’t say ‘just reach me at the library’.)",
    "📮 Email time! This is important... unless it’s your personal inbox for memes.",
    "🔑 What’s your email? No pressure, but I might need it to send you my newsletter. (Just kidding. Or am I?)",
    "💻 Hit me with your email! (Or just write ‘secret agent’—I won’t judge.)",
  ],
  invalidEmail: [
    "😬 Hmm, that doesn’t seem quite right. Let’s try that again, shall we?",
    "🚫 Well, that’s... not quite what I was expecting. Give it another shot!",
    "❌ Uh-oh, that doesn’t look like an email address to me. Let’s try again with something else!",
    "🤨 That’s not quite what I had in mind. Maybe give it another go?",
    "😅 Oops! Looks like something’s off. How about another try?",
    "🔴 That doesn’t seem to be working. Try again and make sure it’s a proper email!",
    "⚠️ Hmm, that’s not quite it. Try again, and let’s get it right this time!",
    "🧐 Something’s not adding up here. Let’s give it another go, yeah?",
  ],
  message: [
    "💭 What’s on your mind? (Besides ‘this is the most entertaining AI I’ve ever met’)",
    "🎤 The mic’s yours! (Don’t actually drop it. Those things are expensive.)",
    "🌟 Spill the beans! (Or don’t. I’m not your therapist, but I’ve got a good ear.)",
    "📝 Got something to say? (No pressure, but I *do* have nothing better to do.)",
    "💬 Your message, your rules. Let’s hear it!",
  ],
  confirmation: [
    "🔍 Let’s double-check: \n\n**Name:** {{name}}\n**Email:** {{email}}\n**Message:** {{message}}\n\nDoes this look good? (Say yes, I already deleted the draft!)",
    '✅ Beep boop! Here’s the lowdown:\n\n📝 {{name}}\n📧 {{email}}\n💬 "{{message}}"\n\nReady to hit send?',
    "🎯 Let’s do a final check! (Because, hey, I didn’t mess this up... right?)\n\n**{{name}}** • **{{email}}**\n*{{message}}*\n\nGood? Good.",
    "✅ Just making sure: **{{name}}** • **{{email}}**\n*{{message}}* - Looks good to me, but I’m not the one hitting send!",
  ],
  goodbye: [
    "🚀 Message launched! Mani’s on it—hopefully faster than your Wi-Fi. (No take-backs!)",
    "✨ And... it’s gone! Your message is now zooming through the web at light speed. Or maybe at Mani’s internet speed. Who knows.",
    "🎉 Success! Your message is off to its new home. Now go enjoy the outside world... I’ve heard it’s nice there.",
    "💌 And... sent! Your message is now forever in the digital universe. Or at least until someone unplugs the router.",
    "🌍 Boom! Your message is out there. Now go enjoy a snack while Mani gets to work.",
  ],
};

export const emailErrorMessages = [
  "📛 Oops! That email looks fishier than a sushi restaurant. Try again!",
  "🤔 Hmm, I think you might have been abducted by aliens while typing that. Mind trying again?",
  "👀 I'm no email expert, but I'm pretty sure that's not how they work. Give it another shot!",
  "🔍 Pro tip: Emails usually have an @ symbol and a domain. Yours seems to be on vacation.",
  "💌 Close, but no cigar! Try entering a real email this time (please?).",
];
